### ISSUE TITLE
How to send an image using this?

### ISSUE THREAD

**Issue by Pikku-a** [Syndace/slixmpp-omemo#1]
Is it possible to send an image using slixmpp-omemo?

Also, is this compatible with the [old version here](https://codeberg.org/poezio/slixmpp-omemo)? Do I need to change any code on my project if I switch to this?

**Comment by Syndace** [comment]
> Is it possible to send an image using slixmpp-omemo?

[XEP-0454](https://xmpp.org/extensions/xep-0454.html) explains how encrypted images are sent with OMEMO, which is compatible with this plugin.

> Also, is this compatible with the [old version here](https://codeberg.org/poezio/slixmpp-omemo)? Do I need to change any code on my project if I switch to this?

No, this is not compatible. You will have to change some of your code.
